services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    networks:
      - rest
    ports:
      - '5432'
  app:
    image: 'docker-rest-mvc:latest'
    build:
      context: .
    ports:
      - '8080'
    networks:
      - rest
    container_name: app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
    depends_on:
      - postgres

networks:
  rest: